brew install curl
brew install git
brew install jq
brew install nvm
brew install peco
brew install rbenv
brew install reattach-to-user-namespace
brew install rmtrash
brew install sqlite
brew install the_silver_searcher
brew install tig
brew install tmux
brew install tree
brew install wget
